---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opengist
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opengist
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opengist
    spec:
      containers:
        - name: opengist
          image: ghcr.io/thomiceli/opengist:latest
          env:
            - name: 'OG_LOG_LEVEL'
              value: 'debug'
          ports:
            - containerPort: 6157